### ISSUE TITLE
Send ctrl + c to terminate a running command

### ISSUE THREAD

**Issue by DiegoAz** [markbirbeck/sublime-text-shell-command#54] opened 2016-03-29 18:54 UTC
Hi, thanks for your plugin

I would like to know It is posibble to configure a command to send some keys, (ctrl+c) to kill a running command like in console?

Something similar to killing gulp tasks from the sublime Gulp package?

https://packagecontrol.io/packages/Gulp#killing-tasks

Lines 399 from this file:
https://github.com/NicoSantangelo/sublime-gulp/blob/473cc77564a3175de7c5d54796a1015295293f4f/gulp.py

**Comment by markbirbeck** [comment] 2016-03-30 10:49
I'm closing this issue since it's a duplicate of #10, but thanks thanks for the insight @DiegoAz ...this approach looks ideal.

**Closed by markbirbeck** 2016-03-30 10:49 UTC
Labels: duplicate
